### PR TITLE
Bug/deployment scope

### LINKED ISSUE #5: [bug] unable to find deployment scope
All workflow runs fail using this action with:
`Exception: [Resolve-TemplateDeploymentScope()] Target scope is resourceGroup, but
resourceGroupName property is not present in deploymentConfig.json file`

Get-Content -Raw collects the file content as a singular string, instead of an array of lines:
https://github.com/climpr/deploy-bicep/blob/008dbaaf4c56908385d1a14a114e9bc1437c3318/src/support-functions.psm1#L195

The subsequent -match here:
https://github.com/climpr/deploy-bicep/blob/008dbaaf4c56908385d1a14a114e9bc1437c3318/src/support-functions.psm1#L201
automatically iterates over an array, returning matches, but since $templateFileContent is no longer an array of lines but a singular string it attempts to match the entire template file. It fails to find targetScope in a valid bicep.main file.

### PR DESCRIPTION
**Pull request by ewlidd**
fixes #5 

it will remove all comments from bicep/bicepparam files with the new function before the rest of the functions iterate over them with regex.
regex search replaced with select-string due to -match having different functionality whether it is a singlular string or an array of lines (from get-content for example)
select-string code by @picccard

### CODE REVIEW

**Review by Dikkekip — APPROVED** [review]
Looks good, thanks for the update

**Review by Dikkekip — APPROVED** [review]
Looks good to me, 
Great work @ewlidd and @picccard

**Comment by ewlidd** [comment]
inserted @picccard's code who wrote the select-string replacement and some pester tests.
added some pester tests of my own for testing more comment scenarios

**Comment by ewlidd** [comment]
pester tests passing. ready for review

**Review by audhage — APPROVED** [review]

**Comment by audhage** [comment]
Did some optimizations on the calling structure of the functions, as well as parameter names. Still passing tests. No fundamental changes though, so merging.

**Pull request merged**
